config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "categories#index"
  # get "categories", to: "categories#index"
  # get "categories/new", to: "categories#new"
  # get "categories/:id", to: "categories#show", as: :category
  # post "categories", to: "categories#create"
  # delete "categories/:id", to: "categories#destroy"
    # get 'categories/:category_id/bookmarks/new', to: 'bookmarks#new'

  resources :categories, except: %i[edit update] do
    resources :bookmarks, only: %i[new create show]
  end
  resources :bookmarks, only: [:destroy]
end

# get 'categories/new', to: "categories#new"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
  
  validates :comment, length: { minimum: 6 }
  validates :recipe_id, presence: true, uniqueness: { scope: :category_id }

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks

  validates :name, :description, presence: true
  validates :rating, numericality: { in: 0..10 }
  validates :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unproccessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comment)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category.id)
      # redirect to show page for the new category (or index page)
    else
      # re render (refresh) the new page (form)
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def category_params
    # takes the params objects, filters it down and returns it
    params.require(:category).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.squarespace-cdn.com/content/v1/645373856396281dfb4b2d17/fd786f13-2ee9-4d62-acf2-9fb188765f84/new-punjab-club-food-spread.jpg?format=1500w);">
  <div class="container">
    <h1><strong>Cookbook Categories |</strong><em> for the </em><strong>| Foodies!</strong></h1>
    <p>A personal Cookbook for your favourite recipes.</p>
  </div>
</div>

<div class="container">
  <div class="d-flex justify-content-between align-items-center my-4">
    <h2> List of Categories</h2> <a class="btn btn-primary"  href="/categories/new">Create Category</a>
  </div>
  <div class="cards">
    <% @categories.each do |category| %>
      <% if category.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path category.photo.key, height: 300, crop: :fill %>')">
          <%= link_to category.name, category_path(category)%>
          <%= link_to "🗑️", category_path(category), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"card-delete-icon" %>
        </div>
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
          <%= link_to category.name, category_path(category)%>
          <%= link_to "🗑️", category_path(category), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"card-delete-icon" %>
        </div>
      <% end %>

    <% end %>
  </div>

</div>

app/views/categories/new.html.erb
<h1>Add a category</h1>
<div class="container">
  <%= simple_form_for @category do |f|%>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% if @category.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @category.photo.key %>')">
    <div class="container">
      <h1><%= @category.name %></h1>
    </div>
  </div>
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.squarespace-cdn.com/content/v1/645373856396281dfb4b2d17/fd786f13-2ee9-4d62-acf2-9fb188765f84/new-punjab-club-food-spread.jpg?format=1500w);">
    <div class="container">
      <h1><%= @category.name %></h1>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn.vectorstock.com/i/750p/59/39/chef-hat-cap-doodle-drawing-vector-50855939.avif" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "new category", new_category_path, class: "nav-link" %>
          </li>

        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>